### PR TITLE
Add design principles, purpose to README

### LINKED ISSUE #2: Develop design principles for and structure of the newsletter

### PR DESCRIPTION
**Pull request by equivalentideas**
This PR can be used to discuss and iterate the design principles (#2) and then add them to the README.

It should include
- an opening description about the job this newsletter exists to do
- a description of the content that the newsletter will contain
- a list of design principles of the newsletter
- a link to information about contributing

Fixes #2.

### CODE REVIEW

**Comment by equivalentideas** [comment]
@henare and I just had a quick brainstorm:

The core group of people who should get value from this are _people interested in changing society through technology_. Jobs that this newsletter should do for these people are:
- provide examples of how technology is being used to create civic change, that they weren't previously aware of
- connect them to other people interested in the things that they are interested in
- reassure them of the positive impact these projects can have
- give them interesting things to read
- provide them with projects that they can use themselves
- let them know about events they can go to

**Comment by henare** [comment]
:metal: JTBD :metal:

**Comment by equivalentideas** [comment]
I've added the purpose and beginning principles. More discussion or merge?

**Comment by henare** [comment]
Looks like a good place to work from - let's merge :+1:

**Pull request merged**
