### PR TITLE
Add credits file that also cheekily includes good links to sources

### PR DESCRIPTION
**Pull request by henare**
Is this a good idea?

### CODE REVIEW

**Comment by equivalentideas** [comment]
I think it's a good idea. These's something a bit odd about that second sentence though. Needs comma's or something.

**Comment by henare** [comment]
Can you take a whack at reworking it @equivalentideas?

**Comment by equivalentideas** [comment]
yep

**Comment by henare** [comment]
I don't think we need to be cheeky here - let's be clear this is the credits/sources list.

**Comment by equivalentideas** [comment]
You read my mind @henare

**Comment by henare** [comment]
Nice :tulip:

**Pull request merged**
