### PR TITLE
August edition

### PR DESCRIPTION
**Pull request by equivalentideas**
Working file for creating the August edition.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Added intro and ready for any feedback @henare

**Comment by equivalentideas** [comment]
Links tested :heavy_check_mark:

**Comment by henare** [comment]
@equivalentideas looks good - I especially like the multiple Civic Patterns references :)

**Comment by equivalentideas** [comment]
:hammer: it into em

**Comment by equivalentideas** [comment]
Thanks @henare I'ma gonna merge this and move it into production.

**Pull request merged**
