### PR TITLE
Contributing guide

### LINKED ISSUE #6: Document process for submitting stories via this repo
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by henare**
Basic start of a contributing guide - do we need anything else?

Fixes #6.

### CODE REVIEW

**Comment by equivalentideas** [comment]
Looking good, I made a few additions to the region sentence.

In the process section, it's not clear to me how someone would include an issue in a pull request.

**Comment by henare** [comment]
> In the process section, it's not clear to me how someone would include an issue in a pull request.

Tried to address this in 8a0f77e5b96735be7901d6816c11148f5f60dce2, what do you think @equivalentideas?

**Comment by equivalentideas** [comment]
That helps, I think we could be even more explicit—mind if I have a go?

**Comment by henare** [comment]
Please! :smiley:

**Comment by equivalentideas** [comment]
Have another squiz at that @henare . I think we should move the process bit (_How we prepare an issue of the newsletter_) to the readme, it's not really useful for people about to lodge an issue, more general.

**Comment by henare** [comment]
> I think we should move the process bit (How we prepare an issue of the newsletter) to the readme, it's not really useful for people about to lodge an issue, more general.

The reason I put that in there was because as a contributor I want to know what happens after I submit something. So maybe (again) I just need to be more direct.

**Comment by equivalentideas** [comment]
Nice.

**Comment by henare** [comment]
Sweet, thanks @equivalentideas. Let's see how that goes :shell:

**Pull request merged**
